app = "ring-intercom-api-lingering-wildflower-6228"
primary_region = "cdg"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "suspend"   # o "off" si quieres 0 cold start siempre
  min_machines_running = 1
  processes = ["app"]

  # (Opcional) límites de concurrencia
  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

# Health check para que no rote tráfico hasta que Nest esté listo
[checks]
  [checks.status]
    grace_period = "30s"      # si tu arranque es más lento, sube a "60s"
    interval = "10s"
    timeout = "2s"
    type = "http"
    method = "GET"
    path = "/health"
    port = 3000
